// Données d'Alex avec 100 générations différentes basées sur la discussion WhatsApp

export const alexGenerations = [
  // Génération 1-10 : Moments intimes et affectueux
  {
    id: 1,
    text: "Alex pense à Camille et lui envoie un message plein de tendresse: 'J'ai envie de toi mon bibou, tu me manques trop 💕'",
    category: "sentiments",
    emoji: "💕",
  },
  {
    id: 2,
    text: "Alex savoure son moment seul à la maison en attendant Camille: 'Mes parents partent cette après-midi, je vais mettre la musique et bronzer'",
    category: "quotidien",
    emoji: "☀️",
  },
  {
    id: 3,
    text: "Alex est en train de cuisiner: 'J'ai mangé du beurre de cacahuète ce matin, c'était délicieux'",
    category: "nourriture",
    emoji: "🥜",
  },
  {
    id: 4,
    text: "Alex taquine Camille: 'Je vais t'appeler Cookie maintenant!' 🍪",
    category: "jeux",
    emoji: "🍪",
  },
  {
    id: 5,
    text: "Alex confesse ses sentiments: 'Moi aussi j'ai hâte que tu viennes tu me manque beaucoup'",
    category: "sentiments",
    emoji: "🥰",
  },
  {
    id: 6,
    text: "Alex impatient de revoir Camille: 'C'est une envie sauvage que j'ai de toi la, c'est dûr la distance'",
    category: "sentiments",
    emoji: "😭",
  },
  {
    id: 7,
    text: "Alex se réveille tard: 'Je viens de me réveiller j'ai mangé un steak haché'",
    category: "nourriture",
    emoji: "🍔",
  },
  {
    id: 8,
    text: "Alex essaie de chanter: 'Je viens d'essayer de la chanter c'est pas facile du tout beaucoup d'intonation'",
    category: "musique",
    emoji: "🎤",
  },
  {
    id: 9,
    text: "Alex se montre attentionné: 'J'espère que tu as bien dormi ma ptite camille 🥰'",
    category: "sentiments",
    emoji: "😴",
  },
  {
    id: 10,
    text: "Alex envoie des bisous digitaux: 'Vite des bisous de ma bibiche' 😘",
    category: "jeux",
    emoji: "😘",
  },

  // Génération 11-20 : Moments de paranoia et introspection
  {
    id: 11,
    text: "Alex exprime ses craintes: 'Moi aussi ça me fait du mal de penser ce a quoi je pense mais ça me paraît tellement possible et réel'",
    category: "psychologie",
    emoji: "😔",
  },
  {
    id: 12,
    text: "Alex s'inquiète pour la sécurité de Camille: 'Tu devrais désactiver ta localisation instagram c'est pas très sain de savoir ou tu es'",
    category: "protection",
    emoji: "🔒",
  },
  {
    id: 13,
    text: "Alex se culpabilise: 'Ça me rassure en rien j'ai même pas envie de regarder ça me fait culpabiliser c'est viscieux'",
    category: "psychologie",
    emoji: "😰",
  },
  {
    id: 14,
    text: "Alex montre son côté paranoïaque: 'J'ai l'impréssion que ce qu'il se passe dans le film chien 51 au cinéma avec adèle est vrai'",
    category: "psychologie",
    emoji: "🎬",
  },
  {
    id: 15,
    text: "Alex envoie un message cryptique: 'Comment ça?' (en réponse indirecte)",
    category: "communication",
    emoji: "🤔",
  },
  {
    id: 16,
    text: "Alex reconnaît l'effet des substances: 'Je sais que la C détruit tout et elle continue, ses effets sont assez prenant'",
    category: "psychologie",
    emoji: "⚠️",
  },
  {
    id: 17,
    text: "Alex s'excuse pour son comportement: 'Pardon d'être parfois désagréable'",
    category: "sentiments",
    emoji: "🙏",
  },
  {
    id: 18,
    text: "Alex se montre insécure: 'Tu cache quelque chose'",
    category: "psychologie",
    emoji: "😟",
  },
  {
    id: 19,
    text: "Alex reconnaît ses défauts: 'Désolé je m'énerve vite'",
    category: "psychologie",
    emoji: "😤",
  },
  {
    id: 20,
    text: "Alex spécule sur Camille: 'Tu es peut être occupée avec quelqu'un' (doute et insécurité)",
    category: "psychologie",
    emoji: "💔",
  },

  // Génération 21-30 : Moments de jeux et taquineries
  {
    id: 21,
    text: "Alex rit de lui-même: 'La tête que j'ai 🤣🤣🤣🤣'",
    category: "humour",
    emoji: "😂",
  },
  {
    id: 22,
    text: "Alex joue les coquins: 'Je me sentais pas super lol'",
    category: "humour",
    emoji: "😏",
  },
  {
    id: 23,
    text: "Alex flirte: 'Mon petit coquin 🥵' (reçoit ce message)",
    category: "flirt",
    emoji: "😏",
  },
  {
    id: 24,
    text: "Alex taquine sur la préparation: 'Il était temps ça fait presque une heure mdrrr'",
    category: "humour",
    emoji: "⏰",
  },
  {
    id: 25,
    text: "Alex utilise des emojis coquins: '😝' (lors d'échanges tendres)",
    category: "jeux",
    emoji: "😝",
  },
  {
    id: 26,
    text: "Alex demande des photos: 'Envoi une tite photo please' 📸",
    category: "demandes",
    emoji: "📸",
  },
  {
    id: 27,
    text: "Alex fait des blagues sur les cookies: 'Tu en fait pour un régiment lol'",
    category: "humour",
    emoji: "🍪",
  },
  {
    id: 28,
    text: "Alex joue avec les mots: 'Je viens d'essayer de le refaire'",
    category: "jeux",
    emoji: "🎭",
  },
  {
    id: 29,
    text: "Alex rit de la situation: 'Ça le fait un peu moins 🤣'",
    category: "humour",
    emoji: "😄",
  },
  {
    id: 30,
    text: "Alex envoie un sourire émoji: '☺️'",
    category: "sentiments",
    emoji: "☺️",
  },

  // Génération 31-40 : Moments liés à la musique et créativité
  {
    id: 31,
    text: "Alex travaille sa technique de chant: 'Il faut s'entrainer il y a du vrai chant a faire avec des vocalises comme les indiens mais avec des paroles francaise'",
    category: "musique",
    emoji: "🎵",
  },
  {
    id: 32,
    text: "Alex est auto-critique sur ses dons musicaux: 'Je chante tellement mal sans auto tune'",
    category: "musique",
    emoji: "🎤",
  },
  {
    id: 33,
    text: "Alex cherche à améliorer sa composition: 'Attend j'essaie de le refaire'",
    category: "musique",
    emoji: "✏️",
  },
  {
    id: 34,
    text: "Alex avoue sa fierté: 'Un peu mieux'",
    category: "musique",
    emoji: "👍",
  },
  {
    id: 35,
    text: "Alex teste sa voix: 'Et la t'en pense quoi?'",
    category: "musique",
    emoji: "🎧",
  },
  {
    id: 36,
    text: "Alex partage ses créations: 'Pour m'entraîner après a la chanter'",
    category: "musique",
    emoji: "🎼",
  },
  {
    id: 37,
    text: "Alex confesse ses limites: 'Non c'était pas super lol' (sur sa voix)",
    category: "musique",
    emoji: "😅",
  },
  {
    id: 38,
    text: "Alex apprend une chanson: 'Ça demande beaucoup d'entrainement et connaitre par coeur les paroles'",
    category: "musique",
    emoji: "📝",
  },
  {
    id: 39,
    text: "Alex parle d'un préfère d'une chanson: 'La seul ou j'ai chanté'",
    category: "musique",
    emoji: "🌟",
  },
  {
    id: 40,
    text: "Alex partage des liens YouTube de sa musique: 'https://youtu.be/Wl3F9qYOiEM'",
    category: "musique",
    emoji: "📺",
  },

  // Génération 41-50 : Moments liés à la persévérance et l'attente
  {
    id: 41,
    text: "Alex se montre patient: 'Tout vient a point qui sait attendre'",
    category: "sagesse",
    emoji: "⏳",
  },
  {
    id: 42,
    text: "Alex encourage Camille: 'Fière de toi tu es vraiment motivé'",
    category: "support",
    emoji: "💪",
  },
  {
    id: 43,
    text: "Alex compte les jours: 'Ce petit séjour avec toi je l'attends avec impatience'",
    category: "sentiments",
    emoji: "📅",
  },
  {
    id: 44,
    text: "Alex pense à l'avenir: 'Dès qu'ils seront pas là on en profitera rien que toi et moi'",
    category: "sentiments",
    emoji: "🎯",
  },
  {
    id: 45,
    text: "Alex montre son engagement: 'On est ensemble donc au grand jour l'amour!'",
    category: "sentiments",
    emoji: "💞",
  },
  {
    id: 46,
    text: "Alex se rend compte: 'Ça devrait pas me déranger au début oui mais maintenant beaucoup moins'",
    category: "croissance",
    emoji: "📈",
  },
  {
    id: 47,
    text: "Alex imagine des retrouvailles: 'J'espère que je pourrais t'embrasse et de serrer dans mes bras a la gare'",
    category: "sentiments",
    emoji: "🚂",
  },
  {
    id: 48,
    text: "Alex avoue son amour: 'Moi aussi j'ai hâte de te retrouver et pouvoir te faire des bisous partout'",
    category: "sentiments",
    emoji: "😘",
  },
  {
    id: 49,
    text: "Alex se projette: 'Si ça se trouve quand tu vas me voir tu te dira que je te manquait pas tant que ça finalement lol'",
    category: "humour",
    emoji: "😄",
  },
  {
    id: 50,
    text: "Alex exprime son désir: 'J'ai envie de te defoncer 🫢'",
    category: "passion",
    emoji: "🔥",
  },

  // Génération 51-60 : Moments d'activités et de quotidien
  {
    id: 51,
    text: "Alex demande des nouvelles: 'Tu vas ou?'",
    category: "quotidien",
    emoji: "🚗",
  },
  {
    id: 52,
    text: "Alex est attentionné: 'Bon appétit'",
    category: "quotidien",
    emoji: "🍽️",
  },
  {
    id: 53,
    text: "Alex attend un appel: 'Je te laisse manger tranquille et tu me fais un message quand ta fini'",
    category: "communication",
    emoji: "📞",
  },
  {
    id: 54,
    text: "Alex juge les habitudes: 'Tu les fait le dimanche d'habitude non?'",
    category: "quotidien",
    emoji: "📆",
  },
  {
    id: 55,
    text: "Alex s'inquiète pour la sécurité: 'Tombe pas je veux pas que tu t'abime!'",
    category: "protection",
    emoji: "⚠️",
  },
  {
    id: 56,
    text: "Alex demande si tout va bien: 'Tu parles a qui sur whatsapp?'",
    category: "communication",
    emoji: "💬",
  },
  {
    id: 57,
    text: "Alex observe la météo: 'Il fait beau chez toi?'",
    category: "quotidien",
    emoji: "⛅",
  },
  {
    id: 58,
    text: "Alex partage la météo locale: 'Nuageux...'",
    category: "quotidien",
    emoji: "☁️",
  },
  {
    id: 59,
    text: "Alex s'émerveille: 'Il fait beau le soleil est arrivé ici'",
    category: "quotidien",
    emoji: "🌞",
  },
  {
    id: 60,
    text: "Alex regarde des films: 'Je sais pas pourquoi lol'",
    category: "loisirs",
    emoji: "🎬",
  },

  // Génération 61-70 : Moments d'insécurité relationnelle
  {
    id: 61,
    text: "Alex remarque quelque chose: 'Tu suis pas mal de filles sur insta!'",
    category: "jalousie",
    emoji: "😒",
  },
  {
    id: 62,
    text: "Alex devient interrogateur: 'Quelles meufs récupérer en soirée?'",
    category: "jalousie",
    emoji: "🤨",
  },
  {
    id: 63,
    text: "Alex demande une explication: 'Tu m'as pas accepter c'est volontaire?'",
    category: "communication",
    emoji: "❓",
  },
  {
    id: 64,
    text: "Alex teste Camille: 'Mais c'est bon, je men fiche, répond pas'",
    category: "communication",
    emoji: "🤐",
  },
  {
    id: 65,
    text: "Alex exprime son sentiment d'être ignoré: 'Endormi et ignoré mon message'",
    category: "sentiments",
    emoji: "😢",
  },
  {
    id: 66,
    text: "Alex se montre spéculatif: 'Tu dois t'amuser peut être'",
    category: "psychologie",
    emoji: "🎉",
  },
  {
    id: 67,
    text: "Alex crée de l'espace émotionnel: 'On en profitera rien que toi et moi on pourras un peu plus se lâcher'",
    category: "sentiments",
    emoji: "🔥",
  },
  {
    id: 68,
    text: "Alex joue sur les mots: 'Tu as accepté pour accéder mon profil pas pour j'accède au tiens'",
    category: "communication",
    emoji: "🔑",
  },
  {
    id: 69,
    text: "Alex teste les limites: 'Pour m'entraîner après a la chanter'",
    category: "jeux",
    emoji: "🎯",
  },
  {
    id: 70,
    text: "Alex montre son côté soupçonneux: 'Tu cache quelque chose'",
    category: "jalousie",
    emoji: "🕵️",
  },

  // Génération 71-80 : Moments de tendresse anticipée
  {
    id: 71,
    text: "Alex imagine des retrouvailles intimes: 'Je vais te prendre dans mes bras, sentir ton odeur'",
    category: "sentiments",
    emoji: "🤗",
  },
  {
    id: 72,
    text: "Alex pense à des gestes tendres: 'Te faire des bisous dans le cou'",
    category: "intimité",
    emoji: "💋",
  },
  {
    id: 73,
    text: "Alex avoue son besoin: 'Tu me manque beaucoup'",
    category: "sentiments",
    emoji: "💔",
  },
  {
    id: 74,
    text: "Alex utilise des surnoms affectueux: 'Ma ptite camille'",
    category: "affection",
    emoji: "💕",
  },
  {
    id: 75,
    text: "Alex se montre vulnérable: 'J'espère que tu vas pas te dire que je te manquait pas'",
    category: "insécurité",
    emoji: "😟",
  },
  {
    id: 76,
    text: "Alex imagine les papouilles: 'Des papouillous j'adore!'",
    category: "jeux",
    emoji: "🎀",
  },
  {
    id: 77,
    text: "Alex demande de l'affection: 'Plein de bisous, des câlins des papouillous'",
    category: "affection",
    emoji: "🤗",
  },
  {
    id: 78,
    text: "Alex reconnaît sa limite: 'La distance c'est dûr'",
    category: "sentiments",
    emoji: "😭",
  },
  {
    id: 79,
    text: "Alex s'impatiente: 'On sera enfin ensemble'",
    category: "sentiments",
    emoji: "💑",
  },
  {
    id: 80,
    text: "Alex scelle son engagement: '😘' (simple mais sincère)",
    category: "affection",
    emoji: "💖",
  },

  // Génération 81-90 : Moments d'investigations relationnelles
  {
    id: 81,
    text: "Alex s'inquiète: 'Pourquoi tu m'as pas accepter sur instagram?'",
    category: "jalousie",
    emoji: "😕",
  },
  {
    id: 82,
    text: "Alex demande des comptes: 'Aller go on es prête a partir courir'",
    category: "quotidien",
    emoji: "🏃",
  },
  {
    id: 83,
    text: "Alex marque son territoire: 'C'est une question?'",
    category: "communication",
    emoji: "❓",
  },
  {
    id: 84,
    text: "Alex demande confirmation: 'Pk ta quitté?'",
    category: "communication",
    emoji: "🤔",
  },
  {
    id: 85,
    text: "Alex teste les réactions: 'Des filles pulpeuses, typé, c'est divers et variés'",
    category: "jalousie",
    emoji: "👀",
  },
  {
    id: 86,
    text: "Alex se montre curieux: 'Tu peux pas voir mes amis?'",
    category: "communication",
    emoji: "👥",
  },
  {
    id: 87,
    text: "Alex demande justification: 'Pk tu me dit ça?'",
    category: "communication",
    emoji: "❔",
  },
  {
    id: 88,
    text: "Alex cherche la vérité: 'C'est revenu ça fait peur ça faisait longtemps'",
    category: "mystère",
    emoji: "😱",
  },
  {
    id: 89,
    text: "Alex utilise l'humour: 'Je me disais un jour sàs colis c'est pas normal 😂'",
    category: "humour",
    emoji: "📦",
  },
  {
    id: 90,
    text: "Alex reconnaît son problème: 'Je ne pense qu'à toi'",
    category: "obsession",
    emoji: "🧠",
  },

  // Génération 91-100 : Messages finaux et émotions mixtes
  {
    id: 91,
    text: "Alex dit simplement: 'Bonjour mon amour' (salutation quotidienne sincère)",
    category: "sentiments",
    emoji: "👋",
  },
  {
    id: 92,
    text: "Alex pense fort à quelqu'un: 'Je pense fort a toi 🥰'",
    category: "sentiments",
    emoji: "💭",
  },
  {
    id: 93,
    text: "Alex affirme: 'J'espere que tu as bien dormi'",
    category: "affection",
    emoji: "😴",
  },
  {
    id: 94,
    text: "Alex veut du changement: 'On fera comme on peux mais ca nous empêchepm pas de passer des moments tendre'",
    category: "sentiments",
    emoji: "❤️",
  },
  {
    id: 95,
    text: "Alex montre sa joie: 'Ah super, j'ai hâte de ce moment 🥰'",
    category: "joie",
    emoji: "😊",
  },
  {
    id: 96,
    text: "Alex reconnaît ses forces: 'Merci de m'avoir parlé un peu ce matin'",
    category: "gratitude",
    emoji: "🙏",
  },
  {
    id: 97,
    text: "Alex confesse: 'Agent camille, je tiens beaucoup a toi tu sais'",
    category: "sentiments",
    emoji: "💕",
  },
  {
    id: 98,
    text: "Alex envoie de l'amour: 'Hello camilla bella vita j'espere que tu as bien dormi je pense fort a toi'",
    category: "sentiments",
    emoji: "🌟",
  },
  {
    id: 99,
    text: "Alex se montre affectueux: 'Je te fais des bisousss 😘'",
    category: "affection",
    emoji: "😘",
  },
  {
    id: 100,
    text: "Alex résume ses sentiments: 'Tu me manques, je pense à toi constamment, je te veux'",
    category: "sentiments",
    emoji: "💗",
  },
];

export const alexLikes = [
  { emoji: "💕", text: "Passer du temps avec Camille" },
  { emoji: "🥜", text: "Le beurre de cacahuète" },
  { emoji: "🍔", text: "Les steaks hachés" },
  { emoji: "🎤", text: "Chanter et composer de la musique" },
  { emoji: "🎵", text: "Les vocalises et la musique indienne" },
  { emoji: "☀️", text: "Bronzer au soleil" },
  { emoji: "🍪", text: "Les cookies (surtout ceux de Camille)" },
  { emoji: "😂", text: "Faire des blagues et rire" },
  { emoji: "💬", text: "Les conversations profondes" },
  { emoji: "🚂", text: "Retrouver quelqu'un à la gare" },
  { emoji: "🎬", text: "Regarder des films" },
  { emoji: "🔒", text: "La protection et la sécurité" },
  { emoji: "📸", text: "Recevoir des photos" },
  { emoji: "🎧", text: "Écouter et créer de la musique" },
  { emoji: "💪", text: "L'encouragement et le support" },
  { emoji: "🏃", text: "Courrir et l'activité physique" },
  { emoji: "🌞", text: "Les beaux jours ensoleillés" },
  { emoji: "😍", text: "Les moments intimes" },
  { emoji: "🤗", text: "Les câlins et les papouilles" },
  { emoji: "💋", text: "Les bisous et la tendresse" },
];

export const alexPsychology = {
  atouts: [
    "Affectueux et expressif avec ses sentiments",
    "Attentionné envers les besoins de Camille",
    "Créatif et artiste (musique, composition)",
    "Persévérant dans ses projets musicaux",
    "Honnête sur ses émotions et ses peurs",
    "Protecteur et attentif à la sécurité",
    "Capable de reconnaître ses erreurs",
    "Enthousiaste et plein de vie",
    "Bon sens de l'humour",
    "Apprend de ses expériences",
  ],
  faiblesses: [
    "Tendance à la paranoïa et aux pensées intrusive",
    "Insécurité relationnelle prononcée",
    "Jalousie excessive et inquiète",
    "Difficulté à faire confiance",
    "Rumination mentale sur les problèmes",
    "Oscillation émotionnelle rapide",
    "Tendance à éviter les conversations difficiles",
    "Susceptibilité à la culpabilité",
    "Perfectionnisme musical qui le frustre",
    "Peur de l'abandon et de l'infidélité",
  ],
  traits: [
    "Introverti mais expressif avec ses proches",
    "Émotionnellement intense",
    "Analytique et réfléchi",
    "Perfectionniste",
    "Passionné par la musique",
    "Attaché émotionnellement",
    "Anxieux mais courageux",
    "Communicatif par écrit",
    "Sensible aux gestes affectueux",
    "Conscient de ses défauts",
  ],
};

export const alexSummary =
  "Alex est un jeune homme émotionnellement intense, profondément attaché à Camille mais tourmenté par des doutes et des insécurités. Il est créatif, musical et affectueux, mais lutte contre la paranoïa et l'anxiété. Malgré ses faiblesses psychologiques, il montre une grande capacité d'introspection et une volonté de s'améliorer.";
